-- Seed realistic grant data
INSERT INTO grants (source, source_id, title, agency, description, eligibility_raw, amount_min, amount_max, deadline, posted_date, category, status, source_url) VALUES

-- Federal grants
('grants_gov', 'HHS-2026-ACF-001',
 'Community Health Worker Training and Certification Program',
 'U.S. Department of Health and Human Services',
 'This program supports the development and implementation of community health worker (CHW) training programs in underserved areas. Funding will be used to establish standardized curricula, provide scholarships for CHW candidates, and build sustainable workforce pipelines in communities with documented health disparities. Priority is given to programs that address chronic disease prevention, maternal health, and mental health access in rural and urban underserved populations.',
 'Eligible applicants include nonprofit organizations with 501(c)(3) status, state and local governments, tribal organizations, and institutions of higher education. Applicants must demonstrate existing community health programs or partnerships with community health centers. Organizations must have been operational for at least 2 years and have an annual budget of at least $100,000. Priority consideration for applicants serving Health Professional Shortage Areas (HPSAs).',
 250000, 750000,
 '2026-06-15T23:59:59Z', '2026-02-01T00:00:00Z',
 ARRAY['health', 'education', 'workforce'],
 'open', 'https://www.grants.gov/example/HHS-2026-ACF-001'),

('grants_gov', 'ED-2026-OESE-002',
 'Innovative Approaches to STEM Education in Rural Schools',
 'U.S. Department of Education',
 'The Department of Education seeks applications from eligible entities to develop and implement innovative STEM education models specifically designed for rural school districts. Projects should address the unique challenges of rural education including geographic isolation, limited broadband access, and teacher recruitment. Funded projects will create replicable models that can be shared with other rural districts nationwide.',
 'Eligible applicants include local educational agencies (LEAs) serving rural communities as defined by NCES locale codes 31-43, nonprofit organizations partnering with rural LEAs, and institutions of higher education with established rural education programs. Applicants must serve student populations where at least 40% qualify for free or reduced-price lunch.',
 100000, 500000,
 '2026-07-01T23:59:59Z', '2026-01-15T00:00:00Z',
 ARRAY['education', 'technology'],
 'open', 'https://www.grants.gov/example/ED-2026-OESE-002'),

('grants_gov', 'EPA-2026-OW-003',
 'Clean Water Infrastructure for Small Communities',
 'U.S. Environmental Protection Agency',
 'EPA is soliciting applications for projects that improve drinking water and wastewater infrastructure in small and disadvantaged communities. Eligible projects include upgrading aging water treatment facilities, replacing lead service lines, implementing green infrastructure for stormwater management, and developing water system consolidation plans. This program prioritizes communities with documented water quality violations and those facing environmental justice concerns.',
 'Eligible applicants include municipalities with populations under 10,000, tribal governments, nonprofit organizations working on behalf of small communities, and regional water authorities serving disadvantaged communities. Applicants must demonstrate community support through letters or resolutions from local government. Cost-sharing of at least 20% is required for non-disadvantaged communities.',
 500000, 2000000,
 '2026-05-30T23:59:59Z', '2026-02-10T00:00:00Z',
 ARRAY['environment', 'infrastructure'],
 'open', 'https://www.grants.gov/example/EPA-2026-OW-003'),

('grants_gov', 'DOL-2026-ETA-004',
 'Workforce Reentry Programs for Justice-Involved Individuals',
 'U.S. Department of Labor',
 'This funding opportunity supports organizations providing comprehensive workforce development services to formerly incarcerated individuals. Programs should include job training, credential attainment, supportive services, mentoring, and employer engagement. Successful applicants will demonstrate evidence-based approaches to reducing recidivism through employment.',
 'Eligible applicants include nonprofit organizations, community-based organizations, faith-based organizations, and local workforce development boards. Applicants must have at least 3 years of experience serving justice-involved populations. Programs must include partnerships with local employers willing to hire program participants.',
 200000, 600000,
 '2026-08-15T23:59:59Z', '2026-02-20T00:00:00Z',
 ARRAY['workforce', 'public_safety'],
 'open', 'https://www.grants.gov/example/DOL-2026-ETA-004'),

('grants_gov', 'USDA-2026-NIFA-005',
 'Farm to School and Community Food Access Initiative',
 'U.S. Department of Agriculture',
 'USDA invites applications for projects that connect local agricultural producers with schools and communities to improve food access and nutrition education. Funded projects may include establishing school gardens, creating farm-to-cafeteria supply chains, developing nutrition education curricula, and supporting community food hubs in food deserts.',
 'Eligible applicants include school districts, nonprofit organizations, tribal organizations, agricultural cooperatives, and state/local government agencies. Applicants must demonstrate partnerships between educational institutions and local food producers. Schools must participate in the National School Lunch Program.',
 50000, 250000,
 '2026-04-30T23:59:59Z', '2026-01-20T00:00:00Z',
 ARRAY['food_agriculture', 'education', 'health'],
 'open', 'https://www.grants.gov/example/USDA-2026-NIFA-005'),

-- State grants
('state', 'CA-OES-2026-001',
 'California Community Resilience and Disaster Preparedness Grant',
 'California Office of Emergency Services',
 'The California OES Community Resilience Program provides funding to local organizations to develop and implement disaster preparedness, response, and recovery plans. Priority areas include wildfire preparedness, earthquake readiness, and climate adaptation for vulnerable populations including elderly residents, non-English speakers, and people with disabilities.',
 'Eligible applicants include California-based nonprofit organizations, local government agencies, tribal organizations, and community-based organizations. Applicants must serve communities in Cal OES-designated high-risk areas. Organizations must have experience in emergency preparedness or community organizing.',
 75000, 300000,
 '2026-06-30T23:59:59Z', '2026-02-15T00:00:00Z',
 ARRAY['public_safety', 'infrastructure'],
 'open', NULL),

('state', 'NY-ARTS-2026-001',
 'New York State Arts and Cultural Engagement Program',
 'New York State Council on the Arts',
 'NYSCA invites applications from arts organizations seeking to expand community engagement through innovative programming. Funded projects should make arts and cultural experiences accessible to underserved populations, including rural communities, low-income neighborhoods, and communities of color. Projects may include public art installations, community theater programs, music education initiatives, and cultural heritage preservation.',
 'Eligible applicants include New York State nonprofit arts and cultural organizations with at least 2 years of programming history. Organizations must demonstrate community engagement and have a track record of serving diverse audiences. Annual operating budget must be under $2 million.',
 25000, 100000,
 '2026-05-15T23:59:59Z', '2026-02-01T00:00:00Z',
 ARRAY['arts_culture', 'education'],
 'open', NULL),

-- Foundation grants
('foundation', 'RWJF-2026-001',
 'Building Health Equity Through Community-Led Solutions',
 'Robert Wood Johnson Foundation',
 'RWJF seeks bold, community-driven projects that address the root causes of health inequity. We are looking for organizations that center the voices and leadership of communities most affected by health disparities. Projects should address social determinants of health including housing, education, employment, and environmental conditions.',
 'Eligible applicants include 501(c)(3) nonprofit organizations, tribal organizations, and government entities. Organizations must demonstrate authentic community engagement and leadership by people with lived experience of health inequities. No minimum budget requirement, but applicants should have capacity to manage federal grants.',
 150000, 500000,
 '2026-07-31T23:59:59Z', '2026-02-05T00:00:00Z',
 ARRAY['health', 'housing', 'environment'],
 'open', NULL),

('foundation', 'GATES-2026-EDU-001',
 'Technology-Enabled Learning for Underserved Students',
 'Bill & Melinda Gates Foundation',
 'This initiative supports innovative uses of technology to improve educational outcomes for students from low-income families. We seek projects that leverage adaptive learning platforms, AI tutoring tools, and digital literacy programs to close achievement gaps. Particular interest in approaches that work in both connected and low-connectivity environments.',
 'Eligible applicants include school districts serving predominantly low-income student populations (60%+ free/reduced lunch), nonprofit education organizations, and education technology companies partnering with schools. Applicants must present evidence-based approaches and agree to participate in external evaluation.',
 200000, 1000000,
 '2026-09-01T23:59:59Z', '2026-02-18T00:00:00Z',
 ARRAY['education', 'technology'],
 'open', NULL),

('foundation', 'KRESGE-2026-ENV-001',
 'Urban Green Infrastructure and Climate Adaptation',
 'The Kresge Foundation',
 'The Kresge Foundation supports projects that advance urban climate resilience through green infrastructure investments. Funded projects should demonstrate how nature-based solutions—such as urban forests, green roofs, permeable surfaces, and restored wetlands—can simultaneously address climate risks, improve public health, and advance equity in historically disinvested neighborhoods.',
 'Eligible applicants include municipal governments, nonprofit organizations, and community development financial institutions (CDFIs). Projects must be located in cities with populations over 50,000 and target neighborhoods with documented environmental justice concerns. Matching funds of at least 1:1 are strongly preferred.',
 300000, 750000,
 '2026-08-01T23:59:59Z', '2026-02-12T00:00:00Z',
 ARRAY['environment', 'infrastructure', 'health'],
 'open', NULL),

-- Closed / upcoming grants for variety
('grants_gov', 'HUD-2025-CPD-006',
 'Community Development Block Grant - Disaster Recovery',
 'U.S. Department of Housing and Urban Development',
 'HUD CDBG-DR funding supports long-term recovery in communities affected by recent federally declared disasters. Funds may be used for housing rehabilitation, economic development, infrastructure repair, and public services in affected areas.',
 'Eligible applicants include state and local governments in presidentially declared disaster areas. Nonprofit organizations may apply as subrecipients through their local government. Must demonstrate unmet recovery needs not addressed by FEMA or insurance.',
 1000000, 5000000,
 '2026-01-31T23:59:59Z', '2025-10-15T00:00:00Z',
 ARRAY['housing', 'infrastructure'],
 'closed', 'https://www.grants.gov/example/HUD-2025-CPD-006'),

('grants_gov', 'DOJ-2026-BJA-007',
 'Smart Policing and Community Trust Initiative',
 'U.S. Department of Justice',
 'BJA seeks applications for programs that build trust between law enforcement and communities through evidence-based policing strategies, community engagement, and transparency initiatives. Funded projects should demonstrate measurable improvements in community-police relations.',
 'Eligible applicants include local government agencies, tribal governments, and nonprofit organizations working in partnership with law enforcement agencies. Applicants must submit letters of commitment from participating law enforcement leadership.',
 150000, 400000,
 '2026-10-01T23:59:59Z', '2026-02-25T00:00:00Z',
 ARRAY['public_safety'],
 'upcoming', 'https://www.grants.gov/example/DOJ-2026-BJA-007');
